### PR TITLE
GitHub Cleanup: Old Fork for Review

### PR DESCRIPTION
**Pull request by pgoldrbx**
- [x] Is it still in use?
- [x] Should it be maintained and kept active?
- [ ] Should it be archived for future reference?
- [ ] Or should it just be deleted with no trace left behind?

### CODE REVIEW

**Comment by pgoldrbx** [comment]
This fork appears to have no modifications or indication of _why_ it was forked, versus using the original module.

**Comment by gautamarora** [comment]
@pgoldrbx hold on this please. i see it being referenced in our slideshow app here: https://github.com/CondeNast/cnt-feature-slideshow/blob/master/package.json#L61

**Comment by johnkpaul** [comment]
Oddly, I am somehow still on notifications for this repo and I'm pretty sure that I remember why this was done.

Enquire.js didn't bake in support for browserify, so this fork probably added it. I assume that there was an upstream PR made as well, but I don't know the status of that.

**Comment by pgoldrbx** [comment]
@johnkpaul — already proving useful! Thanks. I'm sure `enquire.js` has been updated since then for commonjs, so we should evaluate using the original module. @gautamarora — I'll leave this alone for now, but maybe you guys can look into making the change in your app?

**Comment by gautamarora** [comment]
thanks for the background @johnkpaul! @pgoldrbx yes, lets keep this for now.

**Comment by pgoldrbx** [comment]
Got it. closing this issue.

**Pull request closed without merging**
